version: '3.1'

services:
  db:
    image: oracle-xe
    ports:
      - 1521:1521
    volumes:
      - dbadmin:/u01/app/oracle/admin
      - dbdiag:/u01/app/oracle/diag
      - dbrecovery:/u01/app/oracle/fast_recovery_area
      - dbdata:/u01/app/oracle/oradata
      - dboradiag:/u01/app/oracle/oradiag_oracle    
  wildfly:
    image: wildfly
    depends_on: 
      - db
    ports:
      - 8080:8080
      - 9990:9990
      - 8787:8787
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug
    volumes:
       - ~/webapps:/opt/jboss/wildfly/standalone/deployments
volumes:
  dbadmin:
  dbdiag:
  dbrecovery:
  dbdata:
  dboradiag: